# Generated by Django 3.1.1 on 2020-09-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cmpt_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_room', models.CharField(max_length=255)),
                ('slug_detail', models.SlugField(max_length=255)),
                ('No_cmpt', models.CharField(max_length=2)),
                ('board', models.CharField(max_length=255)),
                ('cpu', models.CharField(max_length=255)),
                ('ram', models.CharField(max_length=255)),
                ('hdd', models.CharField(max_length=255)),
                ('ssd', models.CharField(max_length=255)),
                ('psu', models.CharField(max_length=255)),
                ('case', models.CharField(max_length=255)),
                ('monitor', models.CharField(max_length=255)),
                ('gpu', models.CharField(max_length=255)),
                ('count_cpu', models.IntegerField()),
                ('count_ram', models.IntegerField()),
                ('count_hdd', models.IntegerField()),
                ('count_ssd', models.IntegerField()),
                ('count_psu', models.IntegerField()),
                ('count_case', models.IntegerField()),
                ('count_monitor', models.IntegerField()),
                ('count_gpu', models.IntegerField()),
                ('count_program', models.IntegerField()),
                ('count_windows', models.IntegerField()),
                ('count_all', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='options_std',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_room', models.CharField(max_length=3)),
                ('slug_class_room', models.SlugField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='options_tcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=255)),
                ('slug_room', models.SlugField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='repair_cmpt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_room', models.CharField(max_length=255)),
                ('name_aj', models.CharField(max_length=255)),
                ('slug_repair', models.SlugField(max_length=255)),
                ('No_cmpt', models.CharField(max_length=2)),
                ('img_cmpt', models.CharField(max_length=255)),
                ('stat_cmpt', models.CharField(max_length=255)),
                ('detail_repair', models.TextField()),
                ('date_report', models.CharField(max_length=255)),
                ('date_input', models.CharField(max_length=255)),
                ('date_output', models.CharField(max_length=255)),
                ('user_report', models.CharField(max_length=255)),
                ('check_repair', models.TextField()),
                ('repair', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_room', models.CharField(max_length=255)),
                ('slug_report', models.SlugField(max_length=255)),
                ('No_cmpt', models.CharField(max_length=2)),
                ('detail_repair', models.TextField()),
                ('device_repair', models.TextField()),
            ],
        ),
    ]
