# Generated by Django 3.1.1 on 2020-09-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctrl', '0002_auto_20200925_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair_cmpt',
            name='date_input',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='repair_cmpt',
            name='date_output',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='repair_cmpt',
            name='date_report',
            field=models.CharField(max_length=255),
        ),
    ]
