# Generated by Django 3.1.1 on 2020-09-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctrl', '0002_auto_20200927_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmpt_detail',
            name='count_board',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cmpt_detail',
            name='count_internet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cmpt_detail',
            name='count_keyboard',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cmpt_detail',
            name='count_lic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cmpt_detail',
            name='count_mouse',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cmpt_detail',
            name='count_power',
            field=models.IntegerField(default=0),
        ),
    ]
