# Generated by Django 3.1.1 on 2020-09-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctrl', '0003_auto_20200925_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair_cmpt',
            name='class_room',
            field=models.CharField(max_length=255),
        ),
    ]
